name: updater

on:
  schedule: 
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      CF_EMAIL: ${{ secrets.CF_EMAIL }}
      HOSTNAME: ${{ secrets.HOSTNAME }}

    steps:            
      - name: checkout repo content
        uses: actions/checkout@v4.1.7
      - name: setup python
        uses: actions/setup-python@v5.1.1
      - name: execute py script
        run: |
          python cf_updater.py
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
